apiVersion: v1
kind: Secret
metadata:
  name: superset-secret
  namespace: superset
type: Opaque
data:
  db_url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzLw==
  admin_username: YWRtaW4=
  admin_first_name: YWRtaW4=
  admin_last_name: YWRtaW4=
  admin_email: YWRtaW5AYWRtaW4uY29t
  admin_password: c3VwZXJzZXQ=