apiVersion: v1
kind: Service
metadata:
  labels:
    run: superset
  name: superset
  namespace: superset
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8088
  selector:
    run: superset
  sessionAffinity: None
  type: LoadBalancer