apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: postgres
  name: postgres
  namespace: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      run: postgres
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password              
        image: postgres:9.6
        imagePullPolicy: Always
        name: postgres
        ports:
        - containerPort: 5432
          protocol: TCP
        resources: {}
        volumeMounts:
          - name: postgres
            mountPath: /var/lib/postgresql/
        resources:
          limits:
            cpu: 250m
            memory: 500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres