kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: superset
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi