---
- hosts: localhost
  vars:
    state: present
  tasks:
    - name: Generic question with multiple different responses
      shell: echo $ONE_PASSWORD_PASSWORD | op signin my.1password.com ${ONE_PASSWORD_USER} ${ONE_PASSWORD_SECRET_KEY} | awk 'NR<=1'
      register: op_session
    - debug:
        msg: "{{ op_session.stdout }}"
    - name: Setting env var in bash file
      lineinfile:
        path: "~/.bashrc"
        regexp: '^export OP_SESSION_my='
        line: "{{ op_session.stdout }}"
        create: yes
    - name: Source bashrc for op vars
      shell: source ~/.bashrc && op list vaults
      become_user: root
