---
- hosts: localhost
  vars:
    state: present
  tasks:
    - name: Generic question with multiple different responses
      shell: echo $ONE_PASSWORD_PASSWORD | op signin my.1password.com ${ONE_PASSWORD_USER} ${ONE_PASSWORD_SECRET_KEY} | awk 'NR<=1'
      register: op_session
    - name: Setting env var in bash file
      lineinfile:
        path: "~/.bashrc"
        regexp: '^export OP_SESSION_my='
        line: "{{ op_session.stdout }}"
        create: yes
    - name: Setting env var for op
      shell: "source ~/.bashrc"
    - name: Chek whether access has been granted
      shell: "op list vaults"
