---
- hosts: localhost
  vars:
    state: present
  tasks:
    - name: Generic question with multiple different responses
      shell: echo $ONE_PASSWORD_PASSWORD | op signin my.1password.com ${ONE_PASSWORD_USER} ${ONE_PASSWORD_SECRET_KEY} | awk 'NR<=1'
      register: op_session
    - debug:
        msg: "{{ op_session.stdout }}"
    - name: Setting env var in bash file
      lineinfile:
        state: present
        path: "~/.bashrc"
        regexp: '^export OP_SESSION_my='
        line: "{{ op_session.stdout }}"
        create: yes
        insertafter: 'EOF'
    # TODO: Hack for operation, ~/.bashrc should be sourced and isn't inheritable within a complete enviroment
    - name: Source bashrc for op vars
      shell: . ~/.bashrc && op list vaults
    - name: Retrieve password for test
      shell: ". ~/.bashrc && op get item test"
      register: one_password_output
    # TODO: Hack for retrieving password, assume field 1 contains password, field 0 contains username
    - name: Get password
      shell: echo {{ (one_password_output.stdout|from_json).details.fields[1].value }}
      register: one_password_fields
    - debug:
        msg: "{{ one_password_fields }}"
