---
- hosts: localhost
<<<<<<< HEAD
  tasks:
    - name: Generate password
      shell: date +%s | sha256sum | base64 | head -c 64; echo
      register: gen_password
    - name: Store some credentials
      shell: vault kv put secret/hello {{ app }}={{ password }}
      vars:
        app: foo_user
        password: "{{ gen_password.stdout }}"
    - name: Get value from credentials with specific field
      shell: vault kv get -field=foo_user secret/hello
      register: hello_vault
    - debug:
        msg: "{{ hello_vault.stdout }}"
    - name: Delete secret
      shell: vault kv delete secret/hello
=======
  vars:
    state: present
  tasks:
    - name: Retrieve password for test
      debug:
        var: lookup('onepassword', 'test')
>>>>>>> 786e36bacd51b1f389130b10241f4baf3c5851de
