# - import_playbook: password-playbook.yaml
# - import_playbook: terraform/playbook.yaml
# - import_playbook: config-playbook.yaml
# - import_playbook: kubernetes/haepster/playbook.yaml
# - import_playbook: kubernetes/monitoring/playbook.yaml
# - import_playbook: kubernetes/nifi/playbook.yaml
# - import_playbook: kubernetes/kubeflow/playbook.yaml
- import_playbook: kubernetes/autoscaler/playbook.yaml
# - import_playbook: kubernetes/flink/playbook.yaml
<<<<<<< HEAD
# - import_playbook: kubernetes/kafka/playbook.yaml
=======
# - import_playbook: kubernetes/kafka/playbook.yaml
>>>>>>> 786e36bacd51b1f389130b10241f4baf3c5851de
