---
- hosts: localhost
  vars:
    state: present
  tasks:
    - name: Init terraform
      shell: terraform init
    - name: Create workspace if not exists else select it
      shell: "terraform workspace select {{ lookup('env','CLIENT_ID') }} || terraform workspace new {{ lookup('env','CLIENT_ID') }}"
    - terraform:
        project_path: "/var/infrastructure/terraform"
        state: "{{ state }}"
        force_init: yes
        workspace: "{{ lookup('env','CLIENT_ID') }}"
      register: tf_run
    - debug:
        var: tf_run
    - debug:
        var: tf_run.stdout
