---
- hosts: localhost
  vars:
    cred_name: kubeconfig
    state: present
  tasks:
    - name: Init for terraform
      shell: terraform init
    - name: Check if workspace is selected
      shell: terraform workspace list | grep "*" | awk '{ print $2 }'
      register: result
    - debug:
        msg: "{{ result.stdout }}"
    - name: Create workspace if not exists
      shell: "terraform workspace new {{ lookup('env','CLIENT_ID') }}"
      when: "result.stdout != lookup('env','CLIENT_ID')"
    - terraform:
        project_path: "/var/infrastructure/terraform"
        state: "{{ state }}"
        force_init: yes
        workspace: "{{ lookup('env','CLIENT_ID') }}"
      register: tf_run
    - debug:
        var: tf_run.stdout
