---
- hosts: localhost
  vars:
    namespace: velero
    state: present
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
    bucket: ${BACKUP_BUCKET}
    region: ${AWS_REGION}
    clustername: ${CLIENT_ID}-eks-cluster
  tasks:
    - name: Create S3 bucket
      command: "aws s3api create-bucket --bucket {{ bucket }} --region {{ region }} --create-bucket-configuration LocationConstraint={{ region }}"
      when: state == "present"
    # Create namspace if state is present
    - name: "Create ns {{ namespace }}"
      command: "kubectl create ns {{ namespace }}"
      when: state == "present"
    # Import Velero tasks
    - name: "Run Velero tasks"
      import_tasks: "./tasks.yaml"
    # Delete namspace if state is absent
    - name: "Delete ns {{ namespace }}"
      command: "kubectl delete ns {{ namespace }}"
      when: state == "absent"
    - name: Delete S3 bucket
      command: "aws s3api delete-bucket --bucket {{ bucket }} --region {{ region }}"
      when: state == "absent"
