---
- hosts: localhost
  vars:
    namespace: kafka
    state: present
  tasks:
    # Create namspace if state is present
    - name: "Create ns {{ namespace }}"
      command: "kubectl create ns {{ namespace }}"
      when: state == "present"
     # Import Kafka task
    - name: "Run Kafka tasks"
      import_tasks: "./tasks.yaml"
      when: state == "present"
    - name: "Handling monitoring for {{ namespace }}"
      import_tasks: "monitoring/grafana-tasks.yaml"
      when: state == "present"
     # Delete namspace if state is absent
    - name: "Delete ns {{ namespace }}"
      command: "kubectl delete ns {{ namespace }}"
      when: state == "absent"