- name: Delete helm grafana
  shell: "helm delete grafana --purge"
- name: Delete namespace Grafana
  k8s_raw:
    state: "{{ state }}"
    definition: "{{ lookup('template', './deployment/ns.yaml') | from_yaml }}"
<<<<<<< HEAD
- name: Delete Grafana key from 1password
  shell: op delete item grafana-key
  ignore_errors: true
- name: Delete Grafana credentials from 1password
  shell: op delete item grafana
  ignore_errors: true
=======
>>>>>>> 786e36bacd51b1f389130b10241f4baf3c5851de
