{
 "title": "Kubernetes Kafka Overview, Burrow consumer lag stats, Kafka disk usage",
 "description": "Kafka resource usage and consumer lag overview",
 "tags": [ "Kafka" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka log size by topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ]
  },
  {
   "title": "Kafka log size by broker (disk space utilization)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{kubernetes_name=~\"kafka-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{kubernetes_name=~\"kafka-.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{kubernetes_name=~\"kafka-.*\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, pod)(rate(kafka_server_BrokerTopicMetrics_Count{kubernetes_name=~\"kafka-.*\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, pod)(rate(kafka_server_BrokerTopicMetrics_MeanRate{name=\"BytesInPerSec\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, pod)(rate(kafka_server_BrokerTopicMetrics_MeanRate{name=\"BytesOutPerSec\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Underreplicated partitions by topic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic)(kafka_cluster_Partition_Value{name=\"UnderReplicated\",partition=~\".*\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Under ISR Partition Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (kafka_server_ReplicaManager_Value{name=\"UnderMinIsrPartitionCount\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Consumer lag by group",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_FetcherLagMetrics_Value{name=\"ConsumerLag\",partition=~\".*\"}",
     "legendFormat": "{{group}}"
    }
   ]
  }
 ]
}