---
- hosts: localhost
  vars:
    # TODO: inject name from CLIENT_ID + "-eks-cluster"
    clustername: <NAME HERE>
    # TODO: inject aws region where cluster is created
    region: <AWS REGION HERE>
    state: present
  tasks:
    # Import heapster task
    - name: "Run heapster tasks"
      import_tasks: "tasks.yaml"