- name: Create helm install for autoscaler
  shell: "helm install stable/cluster-autoscaler --name autoscaler --set image.tag=v1.3.1 --set rbac.create=true --set autoDiscovery.clusterName={{ clustername }} --set cloudProvider=aws --set awsRegion={{ region }} --set sslCertPath=/etc/kubernetes/pki/ca.crt"
  when: state == "present"