{
 "title": "NiFi ReportingTask",
 "description": "Nifi ReportingTask",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JVM Thread Stats",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(jvm_thread_stats{status=\"state_waiting\"}) / sum(jvm_thread_stats{status=\"count\"}) * 100"
    }
   ]
  },
  {
   "title": "JVM General Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(jvm_general_stats{status=\"total_used\"}) / sum(jvm_general_stats{status=\"total_max\"}) * 100"
    }
   ]
  },
  {
   "title": "Total threads",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(jvm_thread_stats{status=\"count\"})"
    }
   ]
  },
  {
   "title": "Heap usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum (jvm_heap_stats{status=\"usage\"}) by (job)"
    }
   ]
  },
  {
   "title": "JVM heap stats - Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_heap_stats{status=\"used\"}) by (job)",
     "legendFormat": "Total Used"
    },
    {
     "expr": "jvm_heap_stats{status=\"used\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_group_amount_bytes_total{process_group=\"NiFi Flow\", status=\"written\"}",
     "legendFormat": "Bytes Written"
    },
    {
     "expr": "process_group_amount_bytes_total{process_group=\"NiFi Flow\", status=\"received\"}",
     "legendFormat": "Bytes Received"
    },
    {
     "expr": "process_group_amount_bytes_total{process_group=\"NiFi Flow\", status=\"sent\"}",
     "legendFormat": "Bytes Sent"
    }
   ]
  },
  {
   "title": "Total Max vs Total Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_general_stats{status=\"total_max\"})",
     "legendFormat": "Total Max"
    },
    {
     "expr": "sum(jvm_general_stats{status=\"total_used\"})",
     "legendFormat": "Total Used"
    }
   ]
  },
  {
   "title": "Items",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(process_group_amount_items{process_group=\"NiFi Flow\", status=\"output\"}[1m])",
     "legendFormat": "Items Output"
    },
    {
     "expr": "avg_over_time(process_group_amount_items{process_group=\"NiFi Flow\", status=\"queued\"}[1m])",
     "legendFormat": "Items Queued"
    },
    {
     "expr": "avg_over_time(process_group_amount_items{process_group=\"NiFi Flow\", status=\"input\"}[1m])",
     "legendFormat": "Items Input"
    }
   ]
  },
  {
   "title": "FlowFiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_group_amount_flowfiles_total{process_group=\"NiFi Flow\", status=\"sent\"}",
     "legendFormat": "Flowfiles Sent"
    },
    {
     "expr": "process_group_amount_flowfiles_total{process_group=\"NiFi Flow\", status=\"queued\"}",
     "legendFormat": "Flowfiles Queued"
    },
    {
     "expr": "process_group_amount_flowfiles_total{process_group=\"NiFi Flow\", status=\"received\"}",
     "legendFormat": "Flowfiles Received"
    }
   ]
  },
  {
   "title": "Content",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "mbytes", "label": "In MiB" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(process_group_size_content_total{process_group=\"NiFi Flow\", status=\"output\"}[1m]) / 1024 / 1024",
     "legendFormat": "Content Output"
    },
    {
     "expr": "avg_over_time(process_group_size_content_total{process_group=\"NiFi Flow\", status=\"input\"}[1m]) / 1024 / 1024",
     "legendFormat": "Content Input"
    },
    {
     "expr": "avg_over_time(process_group_size_content_total{process_group=\"NiFi Flow\", status=\"queued\"}[1m]) / 1024 / 1024",
     "legendFormat": "Content Queued "
    }
   ]
  }
 ]
}