# This file contains the prerequisites necessary to run the Velero server:
# 1. velero namespace
# 2. velero service account
# 3. RBAC rules to grant permissions to the velero service account
# 4. CRDs for the Velero-specific resources (Backup, Schedule, Restore, etc.)

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backups.velero.io
  labels:
    component: velero
spec:
  group: velero.io
  version: v1
  scope: Namespaced
  names:
    plural: backups
    kind: Backup

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: schedules.velero.io
  labels:
    component: velero
spec:
  group: velero.io
  version: v1
  scope: Namespaced
  names:
    plural: schedules
    kind: Schedule

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: restores.velero.io
  labels:
    component: velero
spec:
  group: velero.io
  version: v1
  scope: Namespaced
  names:
    plural: restores
    kind: Restore

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: downloadrequests.velero.io
  labels:
    component: velero
spec:
  group: velero.io
  version: v1
  scope: Namespaced
  names:
    plural: downloadrequests
    kind: DownloadRequest

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deletebackuprequests.velero.io
  labels:
    component: velero
spec:
  group: velero.io
  version: v1
  scope: Namespaced
  names:
    plural: deletebackuprequests
    kind: DeleteBackupRequest

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podvolumebackups.velero.io
  labels:
    component: velero
spec:
  group: velero.io
  version: v1
  scope: Namespaced
  names:
    plural: podvolumebackups
    kind: PodVolumeBackup

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podvolumerestores.velero.io
  labels:
    component: velero
spec:
  group: velero.io
  version: v1
  scope: Namespaced
  names:
    plural: podvolumerestores
    kind: PodVolumeRestore

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resticrepositories.velero.io
  labels:
    component: velero
spec:
  group: velero.io
  version: v1
  scope: Namespaced
  names:
    plural: resticrepositories
    kind: ResticRepository

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backupstoragelocations.velero.io
  labels:
    component: velero
spec:
  group: velero.io
  version: v1
  scope: Namespaced
  names:
    plural: backupstoragelocations
    kind: BackupStorageLocation

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: volumesnapshotlocations.velero.io
  labels:
    component: velero
spec:
  group: velero.io
  version: v1
  scope: Namespaced
  names:
    plural: volumesnapshotlocations
    kind: VolumeSnapshotLocation

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serverstatusrequests.velero.io
  labels:
    component: velero
spec:
  group: velero.io
  version: v1
  scope: Namespaced
  names:
    plural: serverstatusrequests
    kind: ServerStatusRequest
---
apiVersion: v1
kind: Namespace
metadata:
  name: velero

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero
  namespace: velero
  labels:
    component: velero

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: velero
  labels:
    component: velero
subjects:
  - kind: ServiceAccount
    namespace: velero
    name: velero
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io