---
- hosts: localhost
  vars:
    namespace: prometheus
    state: present
  tasks:
    - name: Create namespace Prometheus
      k8s_raw:
        state: "{{ state }}"
        definition: "{{ lookup('template', './prometheus/ns.yaml') | from_yaml }}"
      when: state == "present"
    - name: Create helm install prometheus
      shell: "helm install -f prometheus/values.yaml stable/prometheus --name prometheus --namespace prometheus"
      when: state == "present"
    - name: Delete helm prometheus
      shell: "helm delete prometheus --purge"
      when: state == "absent"
    - name: Delete namespace Prometheus
      k8s_raw:
        state: "{{ state }}"
        definition: "{{ lookup('template', './prometheus/ns.yaml') | from_yaml }}"
      when: state == "absent"
