- name: Check if chart release exists
  shell: helm get heapster
  register: helm_output
  ignore_errors: true
- debug:
    msg: "{{ helm_output.stdout }}"
- name: Create helm install heapster
  shell: "helm install --name heapster -f deployment/values.yaml stable/heapster"
  when: state == "present" and helm_output.stdout == ""
- name: "Create rbac"
  k8s_raw:
    state: "{{ state }}"
    definition: "{{ lookup('template', './deployment/rbac.yaml') | from_yaml }}"
# TODO: Can't create the cr, already exists and returns 500 error, not sure what to do
# - name: "Create cr"
#   k8s_raw:
#     state: "{{ state }}"
#     definition: "{{ lookup('template', './deployment/cr.yaml') | from_yaml }}"
# TODO: Receiving error, so must ignore it, seems not the best way as well, see above
- name: "Apply cr"
  shell: kubectl apply -f ./deployment/cr.yaml
  ignore_errors: true
- name: Delete helm heapster
  shell: "helm delete heapster --purge"
  when: state == "absent"
